services:
  broker_ba:
    image: eclipse-mosquitto:2.0.18
    container_name: broker_ba-cliente
    ports:
      - "1883:1883"
      - "1884:1884"
    networks:
      - mqtt-net
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_config:/mosquitto/config

  mqtt-client:
    build:
      context: ./app/client
      dockerfile: Dockerfile-client
    container_name: mqtt-client
    restart: unless-stopped
    networks:
      - mqtt-net
    environment:
      - BROKER_ADDRESS=broker_ba
      - BROKER_PORT=1884
    depends_on:
      - broker_ba

networks:
  mqtt-net:
    driver: bridge

volumes:
  mosquitto_data:
  mosquitto_config:
