
services:
  mqtt-client:
    build:
      context: ./app/client
      dockerfile: Dockerfile-client
    container_name: mqtt-client
    restart: unless-stopped
    environment:
      - BROKER_ADDRESS=broker_ba
      - BROKER_PORT=1884
    networks:
      - mqtt-net
networks:
  mqtt-net:
    external: true
