# Dockerfile para o cliente (carro)
FROM python:3.12.3-slim

WORKDIR /app
COPY . .

# (Opcional) Instalar dependências futuras
# RUN pip install -r requirements.txt

CMD ["bash"]

# Obs: Ao iniciar o container, use:
# docker exec -it client-1 bash
# python3 client.py
