# Usa uma imagem oficial do Python como base
FROM python:3.12-slim

# Diretório de trabalho dentro do container
WORKDIR /app

# Copia o script Python para dentro do container
COPY mqtt_client.py .

# Instala a biblioteca Paho MQTT
RUN pip install flask paho-mqtt==2.1.0

# Comando padrão que será executado ao iniciar o container
CMD ["python", "mqtt_client.py"]
