# Usa uma imagem oficial do Python como base
FROM python:3.11-slim

# Diretório de trabalho dentro do container
WORKDIR /app

# Copia o script Python para dentro do container
COPY mqtt_client.py .

# Instala a biblioteca Paho MQTT
RUN pip install --no-cache-dir paho-mqtt

# Comando padrão que será executado ao iniciar o container
CMD ["python", "mqtt_client.py"]
